# Generated by Django 4.2.3 on 2023-12-29 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeoperationform',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
    ]
